# Select image from https://hub.docker.com/_/php/
image: php:7.0

# Select what we should cache
cache:
  paths:
  - vendor/

before_script:
# Install git, the php image doesn't have installed
- apt-get update -yqq
- apt-get install git -yqq

# Install composer
- curl -sS https://getcomposer.org/installer | php

# Install all project dependencies
- php composer.phar install

# Install Xdebug
- pecl install xdebug

# Enable Xdebug
- docker-php-ext-enable xdebug
test:php7:
  script:
  - vendor/bin/phpunit --configuration phpunit.xml --coverage-text --colors=never
  when: manual
